# Generated by Django 4.2.5 on 2024-08-04 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("v_superuser", "0003_alter_profile_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeBetweenSaving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=500)),
                (
                    "class_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_betweens",
                        to="v_superuser.classname",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeBetweenSavingsAttrs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interval_name",
                    models.CharField(
                        choices=[
                            ("save_interval", "Save Interval"),
                            ("telegram_send_interval", "Telegram Send Interval"),
                            ("frontend_send_interval", "Frontend Send Interval"),
                            ("onvif_send_interval", "Onvif Send Interval"),
                            ("mqtt_send_interval", "Mqtt Send Interval"),
                        ],
                        max_length=30,
                    ),
                ),
                ("interval_value", models.IntegerField()),
                (
                    "time_between_saving",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attrs",
                        to="meta_data_processor.timebetweensaving",
                    ),
                ),
            ],
        ),
    ]
