# Generated by Django 4.2.5 on 2024-08-05 01:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meta_data_processor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timebetweensaving",
            options={
                "verbose_name": "TIME BETWEEN SAVINGS",
                "verbose_name_plural": "TIME BETWEEN SAVINGS",
            },
        ),
    ]
