# Generated by Django 4.2.5 on 2024-08-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "param",
                    models.CharField(
                        choices=[("RUN", "Run")], max_length=50, unique=True
                    ),
                ),
            ],
        ),
    ]
