# Generated by Django 4.2.5 on 2024-08-05 01:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activate", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="run",
            options={"verbose_name": "RUN", "verbose_name_plural": "RUN"},
        ),
    ]
