######################################################################################
# observe detecting classes in models:
# model        | classes
# bags         | {0: 'bag'}
# face_hiding  | {0: 'balaclava', 1: 'concealing glasses', 2: 'hand',
#              |  3: 'medicine mask', 4: 'non-concealing glasses',
#              |  5: 'nothing', 6: 'scarf'}
# guns         | {0: 'gun', 1: 'knife'}
# human_fault  | {0: 'fall down'}
# siz          | {0: 'helmet', 1: 'vest', 2: 'head'}
# skeleton     | {0: 'person}
######################################################################################
# enaible port fot rtsp server:
# - 8554
# - 8555
# - 8556
######################################################################################

"1":
    name: "1"
    location_rtspsrc: rtsp://rtsp_video_stream:8557/stream
    location_description: "Camera with fake video"
    framerate: 16
    models: [skeleton, guns, bags, face_hiding, human_fault, siz]
    hlssink_width: 1200
    hlssink_height: 600
    video_width: 1200
    video_height: 600
    port: 8554
    quality: low
    opencv_output_width: 1200
    opencv_output_height: 600
    user_id: None
    user_pw: None
    profiles: ["H264-1", "666"]

"2":
    name: "2"
    location_rtspsrc: rtsp://admin:Admin12345@10.0.10.207:554/profile1/media.smp
    location_description: "Office of laboratory"
    framerate: 16
    models: [skeleton, guns, bags, face_hiding, human_fault, siz]
    hlssink_width: 1200
    hlssink_height: 600
    video_width: 1200
    video_height: 600
    port: 8554
    opencv_output_width: 1200
    opencv_output_height: 600
    quality: low
    user_id: None
    user_pw: None
    profiles: ["H264-2"]

"3":
    name: "3"
    location_rtspsrc: rtsp://service:Admin12345!@10.0.10.209:554/profile2/media.smp
    location_description: "Office 417"
    framerate: 16
    models: [skeleton, guns, bags, face_hiding, human_fault, siz]
    hlssink_width: 1200
    hlssink_height: 600
    video_width: 1200
    video_height: 600
    port: 8554
    opencv_output_width: 1200
    opencv_output_height: 600
    quality: low
    user_id: None
    user_pw: None
    profiles: ["H264-3"]
