backpack:
  model: bags
  text: tns1:VideoAnalytics/Bags/Bag
  text_for_onvif: Bag detected
  text_for_telegram: Обнаружена сумка
bag:
  model: bags
  text: tns1:VideoAnalytics/Bags/Bag
  text_for_onvif: Bag detected
  text_for_telegram: Обнаружена сумка
balaclava:
  model: face_hiding
  text: tns1:VideoAnalytics/FaceHiding
  text_for_onvif: Balaclava detected
  text_for_telegram: Обнаружен человек в балаклаве
big bag:
  model: bags
  text: tns1:VideoAnalytics/Bags/BigBag
  text_for_onvif: Big bag detected
  text_for_telegram: Обнаружена большая сумка
concealing glasses:
  model: face_hiding
  text: tns1:VideoAnalytics/Face_hiding/ManInGlasses
  text_for_onvif: A man with glasses was discovered
  text_for_telegram: Обнаружен человек в очках
fall down:
  model: human_fault
  text: tns1:VideoAnalytics/HumanFault
  text_for_onvif: Person fall down detected
  text_for_telegram: Обнаружен человек в падении
gun:
  model: guns
  text: tns1:VideoAnalytics/Guns/Gun
  text_for_onvif: Gun detected
  text_for_telegram: Обнаружено оружие
hand:
  model: face_hiding
  text: tns1:VideoAnalytics/FaceHiding/Head
  text_for_onvif: Head discovered
  text_for_telegram: Обнаружена голова
handbag:
  model: bags
  text: tns1:VideoAnalytics/Bags/Bag
  text_for_onvif: Bag detected
  text_for_telegram: Обнаружена сумка
hands_up:
  model: skeleton
  text: tns1:VideoAnalytics/Skeleton/ManHandsUp
  text_for_onvif: Person hands up
  text_for_telegram: Человек поднял руки вверх
head:
  model: siz
  text: tns1:VideoAnalytics/Equipment/Head
  text_for_onvif: Head discovered
  text_for_telegram: Обнаружена голова
helmet:
  model: siz
  text: tns1:VideoAnalytics/Equipment/ManInHelmet
  text_for_onvif: Person in the helmet detected
  text_for_telegram: Обнаружен человек в шлеме
knife:
  model: guns
  text: tns1:VideoAnalytics/Guns/ColdGun
  text_for_onvif: Cold gun detected
  text_for_telegram: Обнаружено холодное оружие
medicine mask:
  model: face_hiding
  text: tns1:VideoAnalytics/FaceHiding/ManInMedicineMask
  text_for_onvif: A man was found wearing a medical mask
  text_for_telegram: Обнаружен человек в медицинской маске
non-concealing glasses:
  model: face_hiding
  text: tns1:VideoAnalytics/FaceHiding/ManInNonConcealingGlasses
  text_for_onvif: A man wearing clear glasses was discovered
  text_for_telegram: Обнаружен человек в прозрачных очках
nothing:
  model: face_hiding
  text: tns1:VideoAnalytics/FaceHiding/NothingHidingFace
  text_for_onvif: A man was discovered without hiding his face
  text_for_telegram: Обнаружен человек без сокрытия лица
person:
  model: skeleton
  text: tns1:VideoAnalytics/Skeleton/Person
  text_for_onvif: Person detected
  text_for_telegram: Обнаружен человек
scarf:
  model: face_hiding
  text: tns1:VideoAnalytics/FaceHiding/ManInScarf
  text_for_onvif: A man wearing a scarf was discovered
  text_for_telegram: Обнаружен человек в шарфе
suitcase:
  model: bags
  text: tns1:VideoAnalytics/Bags/Bag
  text_for_onvif: Bag detected
  text_for_telegram: Обнаружена сумка
vest:
  model: siz
  text: tns1:VideoAnalytics/Equipment/ManInVest
  text_for_onvif: Person in the vest detected
  text_for_telegram: Обнаружен человек в жилете
