# Generated by Django 4.2.5 on 2024-08-04 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PathTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        default="/backend/onvif/configs/path_tag.yaml", max_length=500
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PathTagUri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "param",
                    models.CharField(
                        choices=[
                            ("GetSystemDateAndTime", "Getsystemdateandtime"),
                            ("GetCapabilities", "Getcapabilities"),
                            ("GetDeviceInformation", "Getdeviceinformation"),
                            ("GetScopes", "Getscopes"),
                            ("GetServices", "Getservices"),
                            ("GetNetworkInterfaces", "Getnetworkinterfaces"),
                            ("GetDNS", "Getdns"),
                            ("GetProfiles", "Getprofiles"),
                            ("GetStreamUri", "Getstreamuri"),
                            ("GetSnapshotUri", "Getsnapshoturi"),
                            ("GetVideoSources", "Getvideosources"),
                            (
                                "GetVideoSourceConfiguration",
                                "Getvideosourceconfiguration",
                            ),
                            (
                                "GetAudioSourceConfiguration",
                                "Getaudiosourceconfiguration",
                            ),
                            ("GetProfile", "Getprofile"),
                            (
                                "GetMetadataConfigurationOptions",
                                "Getmetadataconfigurationoptions",
                            ),
                            ("GetMetadataConfiguration", "Getmetadataconfiguration"),
                            ("Subscribe", "Subscribe"),
                            ("GetEventProperties", "Geteventproperties"),
                            ("GetAudioSources", "Getaudiosources"),
                            ("Renew", "Renew"),
                            ("Unsubscribe", "Unsubscribe"),
                            (
                                "CreatePullPointSubscription",
                                "Createpullpointsubscription",
                            ),
                            ("PullMessages", "Pullmessages"),
                            (
                                "GetVideoEncoderConfigurationOptions",
                                "Getvideoencoderconfigurationoptions",
                            ),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name_method", models.CharField(max_length=100)),
                (
                    "onvif_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="onvif.pathtag",
                    ),
                ),
            ],
        ),
    ]
