# Generated by Django 4.2.5 on 2024-08-05 01:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("onvif", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pathtag",
            options={"verbose_name": "PATH TAG", "verbose_name_plural": "PATH TAG"},
        ),
    ]
