gun:
  save_interval: 1
  telegram_send_interval: 5
  frontend_send_interval: 5
  onvif_send_interval: 5  
knife:
  save_interval: 1
  telegram_send_interval: 5
  frontend_send_interval: 5
  onvif_send_interval: 5 
fall down:
  save_interval: 1
  telegram_send_interval: 5
  frontend_send_interval: 5
  onvif_send_interval: 5 
bag:
  save_interval: 1
  telegram_send_interval: 5
  frontend_send_interval: 5
  onvif_send_interval: 5
person:
  save_interval: 15
  telegram_send_interval: 15
  frontend_send_interval: 15
  onvif_send_interval: 5 
balaclava:
  save_interval: 5
  telegram_send_interval: 5
  frontend_send_interval: 5
  onvif_send_interval: 5 
concealing glasses:
  save_interval: 5
  telegram_send_interval: 5
  frontend_send_interval: 5
  onvif_send_interval: 5 
hand:
  save_interval: 5
  telegram_send_interval: 5
  frontend_send_interval: 5
  onvif_send_interval: 5 
medicine mask:
  save_interval: 5
  telegram_send_interval: 5
  frontend_send_interval: 5
  onvif_send_interval: 5 
non-concealing glasses:
  save_interval: 5
  telegram_send_interval: 5
  frontend_send_interval: 5
  onvif_send_interval: 5 
nothing:
  save_interval: 5
  telegram_send_interval: 5
  frontend_send_interval: 5
  onvif_send_interval: 5 
scarf:
  save_interval: 5
  telegram_send_interval: 5
  frontend_send_interval: 5
  onvif_send_interval: 5 
helmet:
  save_interval: 5
  telegram_send_interval: 5
  frontend_send_interval: 5
  onvif_send_interval: 5 
vest:
  save_interval: 5
  telegram_send_interval: 5
  frontend_send_interval: 5
  onvif_send_interval: 5 
head:
  save_interval: 5
  telegram_send_interval: 5
  frontend_send_interval: 5
  onvif_send_interval: 5 
hands_up:
  save_interval: 5
  telegram_send_interval: 5
  frontend_send_interval: 5
  onvif_send_interval: 5