# Generated by Django 4.2.5 on 2024-08-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gstream", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cameraattrs",
            name="framerate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cameraattrs",
            name="hlssink_height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cameraattrs",
            name="hlssink_width",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cameraattrs",
            name="location_description",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cameraattrs",
            name="location_rtspsrc",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cameraattrs",
            name="opencv_output_height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cameraattrs",
            name="opencv_output_width",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cameraattrs",
            name="port",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cameraattrs",
            name="video_height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cameraattrs",
            name="video_width",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
