# Generated by Django 4.2.5 on 2024-08-05 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gstream", "0003_remove_commonattrs_image_height"),
    ]

    operations = [
        migrations.CreateModel(
            name="Points",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PoseEstConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_order", models.CharField(max_length=50)),
                ("path", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name": "6. POSE EST",
                "verbose_name_plural": "6. POSE EST",
            },
        ),
        migrations.AlterModelOptions(
            name="cameraconfig",
            options={"verbose_name": "4. CAMERAS", "verbose_name_plural": "4. CAMERAS"},
        ),
        migrations.AlterModelOptions(
            name="colorsconfig",
            options={"verbose_name": "1. COLORS", "verbose_name_plural": "1. COLORS"},
        ),
        migrations.AlterModelOptions(
            name="commonconfig",
            options={"verbose_name": "5. COMMON", "verbose_name_plural": "5. COMMON"},
        ),
        migrations.AlterModelOptions(
            name="modelsconfig",
            options={"verbose_name": "2. MODELS", "verbose_name_plural": "2. MODELS"},
        ),
        migrations.AlterModelOptions(
            name="textconfig",
            options={"verbose_name": "3. TEXTS", "verbose_name_plural": "3. TEXTS"},
        ),
        migrations.CreateModel(
            name="PoseEstAttrs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_skeleton",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "points",
                    models.ManyToManyField(
                        blank=True, null=True, related_name="+", to="gstream.points"
                    ),
                ),
                (
                    "pose_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pose_attrs",
                        to="gstream.poseestconfig",
                    ),
                ),
            ],
        ),
    ]
