# Generated by Django 4.2.5 on 2024-08-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v_superuser", "0006_points"),
        ("gstream", "0004_points_poseestconfig_alter_cameraconfig_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Points",
        ),
        migrations.AlterField(
            model_name="poseestattrs",
            name="points",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="+", to="v_superuser.points"
            ),
        ),
    ]
