# Generated by Django 4.2.5 on 2024-08-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassesNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
            ],
            options={
                "verbose_name": "Class Number (superuser)",
                "verbose_name_plural": "Class Number (superuser)",
            },
        ),
        migrations.CreateModel(
            name="ClassName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("face", "Face"),
                            ("hands", "Hands"),
                            ("legs", "Legs"),
                            ("body", "Body"),
                            ("gun", "Gun"),
                            ("knife", "Knife"),
                            ("bag", "Bag"),
                            ("balaclava", "Balaclava"),
                            ("concealing glasses", "Concealing Glasses"),
                            ("hand", "Hand"),
                            ("medicine mask", "Medicine Mask"),
                            ("non-concealing glasses", "Non Concealing Glasses"),
                            ("nothing", "Nothing"),
                            ("scarf", "Scarf"),
                            ("fall down", "Fall Down"),
                            ("helmet", "Helmet"),
                            ("vest", "Vest"),
                            ("head", "Head"),
                            ("hands_up", "Hands Up"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Names (superuser)",
                "verbose_name_plural": "Class Names (superuser)",
            },
        ),
        migrations.CreateModel(
            name="ModelsName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("skeleton", "Skeleton"),
                            ("guns", "Guns"),
                            ("bags", "Bags"),
                            ("face_hiding", "Face Hiding"),
                            ("human_fault", "Human Fault"),
                            ("siz", "Siz"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "Models Names (superuser)",
                "verbose_name_plural": "Models Names (superuser)",
            },
        ),
    ]
