# Generated by Django 4.2.5 on 2024-08-04 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("v_superuser", "0002_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "verbose_name": "Profiles (superuser)",
                "verbose_name_plural": "Profiles (superuser)",
            },
        ),
    ]
