# Generated by Django 4.2.5 on 2024-08-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v_superuser", "0003_alter_profile_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
