# Generated by Django 4.2.5 on 2024-08-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v_superuser", "0004_alter_profile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classname",
            name="name",
            field=models.CharField(
                choices=[
                    ("person", "Person"),
                    ("face", "Face"),
                    ("hands", "Hands"),
                    ("legs", "Legs"),
                    ("body", "Body"),
                    ("gun", "Gun"),
                    ("knife", "Knife"),
                    ("bag", "Bag"),
                    ("balaclava", "Balaclava"),
                    ("concealing glasses", "Concealing Glasses"),
                    ("hand", "Hand"),
                    ("medicine mask", "Medicine Mask"),
                    ("non-concealing glasses", "Non Concealing Glasses"),
                    ("nothing", "Nothing"),
                    ("scarf", "Scarf"),
                    ("fall down", "Fall Down"),
                    ("helmet", "Helmet"),
                    ("vest", "Vest"),
                    ("head", "Head"),
                    ("hands_up", "Hands Up"),
                    ("big bag", "Big Bag"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
