# Generated by Django 4.2.5 on 2024-08-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v_superuser", "0005_alter_classname_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Points",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
