# Generated by Django 4.2.5 on 2024-08-04 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        default="/backend/telegram/configs/telegram.yaml",
                        max_length=500,
                    ),
                ),
                ("token", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TelegramChatId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.BigIntegerField()),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats_admin_ids",
                        to="telegram.telegramconfig",
                    ),
                ),
            ],
        ),
    ]
